# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
   build:
    say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: circleci/python:3.6.1
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: "install dependencies"
          command: "sudo python3 -m venv venv . venv/bin/activate make install"
      - save_cache:
         paths:
           - ./venv
         key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: "Run link"
          command: ". venv/bin/activatemake lint"
      - run:
          name: "Run tests"
          command: "make test"
